const promptList = [
    "Shibou's metal music",
    "Lurker appears",
    "TastyPi maths",
    //"Edgy Jocose",
    "Meowz friend gc",
    "Cute Usaken",
    "Cannibalism mention",
    "Phobi appears & leaves",
    //"Vovgus & Phobi flirting",
    "\"I miss my wife\"",
    //"Narwhal karaoke",
    "Shad dropping wisdom",
    //"Jocose being a cute bf",
    "Move to #silliness",
    "Ddouble being old",
    "Actually wholesome",
    "Multi convo chat",
    "No romance Meowz",
    "Flustered Cris",
    "Bullied Cris",
    "Mage boy coding/game dev progress",
    "Anonum mentions Project Moon",
    "\"Grumble\"",
    "\"I love my wife\"",
    "Jerry Six Simp",
    "Jerry xkcd comic",
    "Jerry with DnD",
    "Axo & Bee Flirting",
    "\"I'm hungry, Hi hungry\" joke",
    "Usaken acting \"evil\"",
    "Axo dirty minded",
    "Therapy",
    "Ember brainrot",
];
const freeList = [
    "Jocose getting milk",
    "Ellime moment",
    "Anonum backreading",
    "Paige abuse/down",
];
