const promptList = [
    "Time Loop",
    "Vedal Dies for No Reason",
    "Non-Neuroverse Crossover",
    "Zero Tags",
    "Prompt in the Text",
    "No Dialogue",
    "Present Tense Fic",
    "2nd Person",
    "Placeholder Title/Summary",
    "Convoluted Time Travel",
    "Wholesome No Angst",
    "Therapy",
    "NFC Member Appears",
    "Mature Fic",
    "Zoomer Lingo",
    "Obvious Author",
    "Neuro/Evil/Vedal Not Main Character",
    "Rum Mentioned",
    "Exceedingly Niche Reference",
    "Under 1K Words",
    "Exactly 4K Words",
    "Song/Lyric in Text",
    "5 or More Neuroverse Characters",
    "Self-Deprecating AN",
    "Fancy Formatting",
    "Over Ten Tags",
    "Free-Form Tag Usage",
    "Non-Linear Story",
    "Twist Ending",
    "Title Drop",
    "NFC Server Reference",
    "Dreams",
    "Monologuing",
];
const freeList = [
    "Angst",
];