const promptList = [
    "Vedal Dies for No Reason",
    "Non-Neuroverse Crossover",
    "Zero Tags",
    "Prompt in the Text",
    "No Dialogue",
    "Present Tense Fic",
    "2nd Person",
    "Placeholder Title/Summary",
    "Wholesome No Angst",
    "Therapy",
    "Mature Fic",
    "Zoomer Lingo",
    "Obvious Author",
    "Neuro/Evil/Vedal Not Main Character",
    "Rum Mentioned",
    "Super Niche Reference",
    "Under 1K Words",
    "Exactly 4K Words",
    "Song/Lyric in Text",
    "5 or More Neuroverse Characters",
    "Self-Deprecating Author Note",
    "Fancy Formatting",
    "Over Ten Tags",
    "Free-Form Tag Usage",
    "Twist Ending",
    "Title Drop",
    "NFC Server Reference",
    "Monologuing",
    "Obscure but Approved Tags"
];
const freeList = [
    "Angst",
    "Is Neuroverse :NOWAYING:"
];